-- 코드를 입력하세요
SELECT fo.PRODUCT_ID, fp.PRODUCT_NAME, SUM(fp.PRICE * fo.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER fo
INNER JOIN FOOD_PRODUCT fp ON fo.PRODUCT_ID = fp.PRODUCT_ID
WHERE TO_CHAR(fo.PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY fo.PRODUCT_ID, fp.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, fo.PRODUCT_ID ASC