-- 코드를 작성해주세요
SELECT 
    YEAR(e1.DIFFERENTIATION_DATE) AS YEAR, 
    (max_data.MAX_SIZE - e1.SIZE_OF_COLONY) AS YEAR_DEV, 
    e1.ID
FROM ECOLI_DATA e1
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) max_data 
ON YEAR(e1.DIFFERENTIATION_DATE) = max_data.YEAR
ORDER BY YEAR, YEAR_DEV;