-- 코드를 입력하세요
SELECT ICECREAM_INFO.FLAVOR FROM ICECREAM_INFO
LEFT OUTER JOIN FIRST_HALF ON ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR
WHERE TOTAL_ORDER >= 3000 AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;