-- 코드를 입력하세요
SELECT TITLE, board.BOARD_ID, reply.REPLY_ID, reply.WRITER_ID, reply.CONTENTS, date_format(reply.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD board
JOIN USED_GOODS_REPLY reply ON board.BOARD_ID = reply.BOARD_ID
WHERE YEAR(board.CREATED_DATE) = 2022 AND MONTH(board.CREATED_DATE) = 10
ORDER BY CREATED_DATE ASC, TITLE ASC;